version: "3.5"

services:

  # Hue

  hue:
    image: johannestang/hue:4.3.0-presto0.215
    restart: always
    depends_on:
      - hue-postgres
    ports:
      - "8888:8888"
    volumes:
      - ./config/pseudo-distributed.ini:/hue/desktop/conf/pseudo-distributed.ini
    networks:
      - hue_net

  hue-postgres:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_DB: hue
      POSTGRES_PASSWORD: hue
      POSTGRES_USER: hue
    volumes:
      - ${DATADIR}/hue/postgres:/var/lib/postgresql/data
    networks:
      - hue_net

networks:
  hue_net:
    external:
      name: bigdatanet
